package br.com.sysdesc.util.constants;

public class MensagemUtilConstants {

	private MensagemUtilConstants() {
	}

	public static final String MENSAGEM_ARQUIVO_CONFIGURACOES_NAO_ENCONTRADO = "MENSAGEM_ARQUIVO_CONFIGURACOES_NAO_ENCONTRADO";
	public static final String MENSAGEM_DRIVER_NAO_ENCONTRADO = "MENSAGEM_DRIVER_NAO_ENCONTRADO";
	public static final String MENSAGEM_CONEXAO_INVALIDA = "MENSAGEM_CONEXAO_INVALIDA";
	public static final String MENSAGEM_TIPO_DADO_INVALIDO = "MENSAGEM_TIPO_DADO_INVALIDO";
	public static final String MENSAGEM_INSIRA_NUMERO_CASAS_DECIMAIS = "MENSAGEM_INSIRA_NUMERO_CASAS_DECIMAIS";
	public static final String MENSAGEM_SELECIONE_UMA_FORMATACAO = "MENSAGEM_SELECIONE_UMA_FORMATACAO";
	public static final String MENSAGEM_PESQUISA_NAO_CONFIGURADA = "MENSAGEM_PESQUISA_NAO_CONFIGURADA";

	public static final String MENSAGEM_NENHUM_REGISTRO_ENCONTRADO = "MENSAGEM_NENHUM_REGISTRO_ENCONTRADO";

	public static final String MENSAGEM_ERRO_BUSCAR_PROPRIEDADES_CONEXAO = "MENSAGEM_ERRO_BUSCAR_PROPRIEDADES_CONEXAO";
	public static final String MENSAGEM_INSIRA_DESCRICAO_VALIDA = "MENSAGEM_INSIRA_DESCRICAO_VALIDA";
	public static final String MENSAGEM_LOG_PROPRIEDADES_CONEXAO = "MENSAGEM_LOG_PROPRIEDADES_CONEXAO";

	public static final String MENSAGEM_SELECIONE_APENAS_UM_REGISTRO = "MENSAGEM_SELECIONE_APENAS_UM_REGISTRO";
	public static final String MENSAGEM_SELECIONE_UM_REGISTRO = "MENSAGEM_SELECIONE_UM_REGISTRO";
	public static final String MENSAGEM_SELECIONE_PERMISSAO_PESQUISA = "MENSAGEM_SELECIONE_PERMISSAO_PESQUISA";
	public static final String MENSAGEM_INSIRA_PAGINACAO_VALIDA = "MENSAGEM_INSIRA_PAGINACAO_VALIDA";
	public static final String MENSAGEM_PEQUISA_VALIDA = "MENSAGEM_PEQUISA_VALIDA";
	public static final String MENSAGEM_SELECIONE_CAMPO_PESQUISA = "MENSAGEM_SELECIONE_CAMPO_PESQUISA";

}
