package br.com.sysdesc.util.constants;

public class MensagemConstants {

    private MensagemConstants() {
    }

    public static final String MENSAGEM_ARQUIVO_CONFIGURACOES_NAO_ENCONTRADO = "MENSAGEM_ARQUIVO_CONFIGURACOES_NAO_ENCONTRADO";
    public static final String MENSAGEM_DRIVER_NAO_ENCONTRADO = "MENSAGEM_DRIVER_NAO_ENCONTRADO";
    public static final String MENSAGEM_CONEXAO_INVALIDA = "MENSAGEM_CONEXAO_INVALIDA";
    public static final String MENSAGEM_TIPO_DADO_INVALIDO = "MENSAGEM_TIPO_DADO_INVALIDO";
    public static final String MENSAGEM_INSIRA_NUMERO_CASAS_DECIMAIS = "MENSAGEM_INSIRA_NUMERO_CASAS_DECIMAIS";
    public static final String MENSAGEM_SELECIONE_UMA_FORMATACAO = "MENSAGEM_SELECIONE_UMA_FORMATACAO";
    public static final String MENSAGEM_PESQUISA_NAO_CONFIGURADA = "MENSAGEM_PESQUISA_NAO_CONFIGURADA";

    public static final String MENSAGEM_INSIRA_MAXIMO_DIAS_PAGAMENTO = "MENSAGEM_INSIRA_MAXIMO_DIAS_PAGAMENTO";
    public static final String MENSAGEM_SELECIONE_FORMA_PROTESTO = "MENSAGEM_SELECIONE_FORMA_PROTESTO";
    public static final String MENSAGEM_SELECIONE_FORMA_MULTA = "MENSAGEM_SELECIONE_FORMA_MULTA";
    public static final String MENSAGEM_SELECIONE_FORMA_JUROS = "MENSAGEM_SELECIONE_FORMA_JUROS";
    public static final String MENSAGEM_DIAS_PROTESTO_MAIOR_ZERO = "MENSAGEM_DIAS_PROTESTO_MAIOR_ZERO";
    public static final String MENSAGEM_DIAS_JURO_MAIOR_ZERO = "MENSAGEM_DIAS_JURO_MAIOR_ZERO";
    public static final String MENSAGEM_VALOR_JURO_MAIOR_ZERO = "MENSAGEM_VALOR_JURO_MAIOR_ZERO";
    public static final String MENSAGEM_DIAS_MULTA_MAIOR_ZERO = "MENSAGEM_DIAS_MULTA_MAIOR_ZERO";
    public static final String MENSAGEM_VALOR_MULTA_MAIOR_ZERO = "MENSAGEM_VALOR_MULTA_MAIOR_ZERO";

    public static final String MENSAGEM_NENHUM_REGISTRO_ENCONTRADO = "MENSAGEM_NENHUM_REGISTRO_ENCONTRADO";

    public static final String MENSAGEM_CONFIGURACOES_INVALIDAS = "MENSAGEM_CONFIGURACOES_INVALIDAS";
    public static final String MENSAGEM_ERRO_BUSCAR_PROPRIEDADES_CONEXAO = "MENSAGEM_ERRO_BUSCAR_PROPRIEDADES_CONEXAO";
    public static final String MENSAGEM_SELECIONE_ESTADO = "MENSAGEM_SELECIONE_ESTADO";
    public static final String MENSAGEM_INSIRA_DESCRICAO_VALIDA = "MENSAGEM_INSIRA_DESCRICAO_VALIDA";
    public static final String MENSAGEM_LOG_PROPRIEDADES_CONEXAO = "MENSAGEM_LOG_PROPRIEDADES_CONEXAO";

    public static final String MENSAGEM_INSIRA_NOME = "MENSAGEM_INSIRA_NOME";
    public static final String MENSAGEM_SELECIONE_TIPO_CLIENTE = "MENSAGEM_SELECIONE_TIPO_CLIENTE";
    public static final String MENSAGEM_INSIRA_CPF = "MENSAGEM_INSIRA_CPF";
    public static final String MENSAGEM_CPF_INVALIDO = "MENSAGEM_CPF_INVALIDO";
    public static final String MENSAGEM_INSIRA_CNPJ = "MENSAGEM_INSIRA_CNPJ";
    public static final String MENSAGEM_CNPJ_INVALIDO = "MENSAGEM_CNPJ_INVALIDO";
    public static final String MENSAGEM_SELECIONE_CIDADE = "MENSAGEM_SELECIONE_CIDADE";
    public static final String MENSAGEM_INSIRA_ENDERECO = "MENSAGEM_INSIRA_ENDERECO";
    public static final String MENSAGEM_INSIRA_NUMERO = "MENSAGEM_INSIRA_NUMERO";
    public static final String MENSAGEM_INSIRA_BAIRRO = "MENSAGEM_INSIRA_BAIRRO";
    public static final String MENSAGEM_INSIRA_CEP = "MENSAGEM_INSIRA_CEP";
    public static final String MENSAGEM_SELECIONE_SEXO = "MENSAGEM_SELECIONE_SEXO";
    public static final String MENSAGEM_SELECIONE_SITUACAO = "MENSAGEM_SELECIONE_SITUACAO";

    public static final String MENSAGEM_INSIRA_UF_VALIDA = "MENSAGEM_INSIRA_UF_VALIDA";

    public static final String MENSAGEM_INSIRA_USUARIO = "MENSAGEM_INSIRA_USUARIO";
    public static final String MENSAGEM_USUARIO_NAO_ENCONTADO = "MENSAGEM_USUARIO_NAO_ENCONTADO";
    public static final String MENSAGEM_SELECIONE_CLIENTE = "MENSAGEM_SELECIONE_CLIENTE";
    public static final String MENSAGEM_CLIENTE_COM_LOGIN = "MENSAGEM_CLIENTE_COM_LOGIN";

    public static final String MENSAGEM_SELECIONE_PERMISSAO_PESQUISA = "MENSAGEM_SELECIONE_PERMISSAO_PESQUISA";
    public static final String MENSAGEM_INSIRA_PAGINACAO_VALIDA = "MENSAGEM_INSIRA_PAGINACAO_VALIDA";
    public static final String MENSAGEM_PEQUISA_VALIDA = "MENSAGEM_PEQUISA_VALIDA";
    public static final String MENSAGEM_SELECIONE_CAMPO_PESQUISA = "MENSAGEM_SELECIONE_CAMPO_PESQUISA";

    public static final String MENSAGEM_SELECIONE_PESQUISA = "MENSAGEM_SELECIONE_PESQUISA";
    public static final String MENSAGEM_SELECIONE_APENAS_UM_REGISTRO = "MENSAGEM_SELECIONE_APENAS_UM_REGISTRO";
    public static final String MENSAGEM_SELECIONE_UM_REGISTRO = "MENSAGEM_SELECIONE_UM_REGISTRO";

    public static final String MENSAGEM_SELECIONE_FIELD = "MENSAGEM_SELECIONE_FIELD";
    public static final String MENSAGEM_SELECIONE_FORMATACAO = "MENSAGEM_SELECIONE_FORMATACAO";
    public static final String MENSAGEM_INSIRA_TAMANHO_VALIDO = "MENSAGEM_INSIRA_TAMANHO_VALIDO";

    public static final String MENSAGENS_PERMISSOES_SALVAS = "MENSAGENS_PERMISSOES_SALVAS";

    public static final String MENSAGEM_ATUALIZAR_VERSAO = "MENSAGEM_ATUALIZAR_VERSAO";
    public static final String MENSAGEM_THREAD_VERSAO_INTEROMPIDA = "MENSAGEM_THREAD_VERSAO_INTEROMPIDA";
    public static final String MENSAGEM_LOG_GERANDO_ARQUIVO = "MENSAGEM_LOG_GERANDO_ARQUIVO";
    public static final String MENSAGEM_LOG_ARQUIVO_DA_VERSAO = "MENSAGEM_LOG_ARQUIVO_DA_VERSAO";
    public static final String MENSAGEM_LOG_VERSAO_NAO_PODE_SER_GERADO = "MENSAGEM_LOG_VERSAO_NAO_PODE_SER_GERADO";

    public static final String MENSAGEM_INSIRA_DATA_ADMISSAO = "MENSAGEM_INSIRA_DATA_ADMISSAO";
    public static final String MENSAGEM_INSIRA_MODALIDADE = "MENSAGEM_INSIRA_MODALIDADE";
    public static final String MENSAGEM_SELECIONE_PROCEDENCIA = "MENSAGEM_SELECIONE_PROCEDENCIA";
    public static final String MENSAGEM_INSIRA_SALARIO = "MENSAGEM_INSIRA_SALARIO";
    public static final String MENSAGEM_INSIRA_CARGO = "MENSAGEM_INSIRA_CARGO";
    public static final String MENSAGEM_FUNCIONARIO_CADASTRADO = "MENSAGEM_FUNCIONARIO_CADASTRADO";
    public static final String MENSAGEM_PACIENTE_CADASTRADO = "MENSAGEM_PACIENTE_CADASTRADO";
    public static final String MENSAGEM_PACIENTE_NAO_ENCONTRADO = "MENSAGEM_PACIENTE_NAO_ENCONTRADO";
    public static final String MENSAGEM_SELECIONE_GRUPO = "MENSAGEM_SELECIONE_GRUPO";

    public static final String MENSAGEM_INSIRA_RG = "MENSAGEM_INSIRA_RG";
    public static final String MENSAGEM_INSIRA_DATA_NASCIMENTO = "MENSAGEM_INSIRA_DATA_NASCIMENTO";
    public static final String MENSAGEM_DATA_EVOLUCAO_INVALIDA = "MENSAGEM_DATA_EVOLUCAO_INVALIDA";
    public static final String MENSAGEM_EVOLUCAO_NAO_INFORMADA = "MENSAGEM_EVOLUCAO_NAO_INFORMADA";
    public static final String MENSAGEM_INSIRA_NOME_PAI = "MENSAGEM_INSIRA_NOME_PAI";
    public static final String MENSAGEM_INSIRA_NOME_MAE = "MENSAGEM_INSIRA_NOME_MAE";
    public static final String MENSAGEM_SELECIONE_NATURALIDADE = "MENSAGEM_SELECIONE_NATURALIDADE";
    public static final String MENSAGEM_INSIRA_CELULAR = "MENSAGEM_INSIRA_CELULAR";
    public static final String MENSAGEM_INSIRA_EMAIL = "MENSAGEM_INSIRA_EMAIL";
    public static final String MENSAGEM_SELECIONE_ESTADO_CIVIL = "MENSAGEM_SELECIONE_ESTADO_CIVIL";
    public static final String MENSAGEM_SELECIONE_ESCOLARIDADE = "MENSAGEM_SELECIONE_ESCOLARIDADE";
    public static final String MENSAGEM_SELECIONE_RACA = "MENSAGEM_SELECIONE_RACA";
    public static final String MENSAGEM_SELECIONE_RELIGIAO = "MENSAGEM_SELECIONE_RELIGIAO";
    public static final String MENSAGEM_INSIRA_HISTORICO_VALIDO = "MENSAGEM_INSIRA_HISTORICO_VALIDO";
    public static final String MENSAGEM_INSIRA_CARTAO_SUS = "MENSAGEM_INSIRA_CARTAO_SUS";
    public static final String MENSAGEM_INSIRA_OCUPACAO_INSS = "MENSAGEM_INSIRA_OCUPACAO_INSS";
    public static final String MENSAGEM_SELECIONE_FORMA_PAGAMAMENTO = "MENSAGEM_SELECIONE_FORMA_PAGAMAMENTO";
    public static final String MENSAGEM_INSIRA_NUMERO_DIAS = "MENSAGEM_INSIRA_NUMERO_DIAS";
    public static final String MENSAGEM_INSIRA_VALOR_PARCELAS = "MENSAGEM_INSIRA_VALOR_PARCELAS";
    public static final String MENSAGEM_INSIRA_NUMERO_PARCELAS = "MENSAGEM_INSIRA_NUMERO_PARCELAS";
    public static final String MENSAGEM_SELECIONE_BANCO = "MENSAGEM_SELECIONE_BANCO";
    public static final String MENSAGEM_INSIRA_AGENCIA_VALIDA = "MENSAGEM_INSIRA_AGENCIA_VALIDA";
    public static final String MENSAGEM_INSIRA_CONTA_VALIDA = "MENSAGEM_INSIRA_CONTA_VALIDA";
    public static final String MENSAGEM_SELECIONE_PACIENTE = "MENSAGEM_SELECIONE_PACIENTE";
    public static final String MENSAGEM_SELECIONE_FORMA_PAGAMENTO = "MENSAGEM_SELECIONE_FORMA_PAGAMENTO";
    public static final String MENSAGEM_INSIRA_VALOR_MENSALIDADE = "MENSAGEM_INSIRA_VALOR_MENSALIDADE";
    public static final String MENSAGEM_INSIRA_DIAS_ANTECEDENCIA = "MENSAGEM_INSIRA_DIAS_ANTECEDENCIA";
    public static final String MENSAGEM_INSIRA_DIA_VENCIMENTO = "MENSAGEM_INSIRA_DIA_VENCIMENTO";
    public static final String MENSAGEM_SELECIONE_SALDO = "MENSAGEM_SELECIONE_SALDO";
    public static final String MENSAGEM_CONFIGURACOES_SALVAS = "MENSAGEM_CONFIGURACOES_SALVAS";
    public static final String MENSAGEM_SELECIONE_FORMA_GERACAO = "MENSAGEM_SELECIONE_FORMA_GERACAO";
    public static final String MENSAGEM_SELECIONE_CONTA_CLIENTES = "MENSAGEM_SELECIONE_CONTA_CLIENTES";
    public static final String MENSAGEM_SELECIONE_CONTA_RECEITA = "MENSAGEM_SELECIONE_CONTA_RECEITA";
    public static final String MENSAGEM_CONFIGURAR_PARAMETROS = "MENSAGEM_CONFIGURAR_PARAMETROS";
    public static final String MENSAGEM_MAXIMO_DIAS_EMAIL = "MENSAGEM_MAXIMO_DIAS_EMAIL";
    public static final String MENSAGEM_INSIRA_SENHA = "MENSAGEM_INSIRA_SENHA";
    public static final String MENSAGEM_ERRO_CONFIGURAR_EMAIL = "MENSAGEM_ERRO_CONFIGURAR_EMAIL";
    public static final String BANCO_NAO_SUPORTADO_BOLETO = "BANCO_NAO_SUPORTADO_BOLETO";
    public static final String NUMERO_INSTRUCAO_PAGAMENTO_INVALIDA = "NUMERO_INSTRUCAO_PAGAMENTO_INVALIDA";
    public static final String MENSAGEM_BANCO_NAO_INFORMADO = "MENSAGEM_BANCO_NAO_INFORMADO";
    public static final String MENSAGEM_INSIRA_CARTEIRA = "MENSAGEM_INSIRA_CARTEIRA";
    public static final String MENSAGEM_INSIRA_NOSSO_NUMERO = "MENSAGEM_INSIRA_NOSSO_NUMERO";
    public static final String MENSAGEM_CONFIGURACAO_BOLETO_INEXISTENTE = "MENSAGEM_CONFIGURACAO_BOLETO_INEXISTENTE";
    public static final String MENSAGEM_ERRO_PROCESSAMENTO_DIARIO = "MENSAGEM_ERRO_PROCESSAMENTO_DIARIO";
    public static final String MENSAGEM_CONFIGURAR_PARAMETROS_MENSALIDADE = "MENSAGEM_CONFIGURAR_PARAMETROS_MENSALIDADE";
    public static final String MENSAGEM_COBRANCA_MENSALIDADE_NAO_ENCONTADA = "MENSAGEM_COBRANCA_MENSALIDADE_NAO_ENCONTADA";
    public static final String MENSAGEM_GERAR_LOTE = "MENSAGEM_GERAR_LOTE";
    public static final String MENSAGEM_VALIDACAO_DIAS_ANTECEDENCIA = "MENSAGEM_VALIDACAO_DIAS_ANTECEDENCIA";
    public static final String MENSAGEM_PROCESSO_INTEROMPIDO_USUARIO = "MENSAGEM_PROCESSO_INTEROMPIDO_USUARIO";
    public static final String MENSAGEM_MENSALIDADE_NAO_ENCONTRADA = "MENSAGEM_MENSALIDADE_NAO_ENCONTRADA";

}
